### ISSUE TITLE
babel 2.10.* - does not compile catalogs

### ISSUE THREAD

**Issue by mb-wali** [python-babel/babel#880]
## Overview Description
We are using babel latest, in our CI to publish to `pypi`, one of our steps in github actions, is to build a package. that has a command  `compile_catalog` to compile our translation catalogs before packaging. 
since the release of `2.10.*` this does not create the `.mo` files anymore, it just prints out `running compile_catalog` and skips the part that it creates the files. although it works in our local environment but does not work on Github actions.

## ci template
```yml
jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel babel
      - name: Build package
        run: |
          python setup.py compile_catalog sdist bdist_wheel
```
Did we miss any configurations? 
is there any way to debug this process?
internal issue inveniosoftware/invenio-app-rdm#1675
